export interface ApsOrderGoodsBomKittingVersionOrder {
  kittingVersionId: string | undefined
  orderId: string | undefined
  orderNo: string | undefined
  kittingRate: string | undefined
  kittingStatus: string | undefined
  kittingMissingBom: string | undefined
  orderField01: string | undefined
  orderField02: string | undefined
  orderField03: string | undefined
  orderField04: string | undefined
  orderField05: string | undefined
  orderField06: string | undefined
  orderField07: string | undefined
  orderField08: string | undefined
  orderField09: string | undefined
  orderField10: string | undefined
  orderField11: string | undefined
  orderField12: string | undefined
  orderField13: string | undefined
  orderField14: string | undefined
  orderField15: string | undefined
  orderField16: string | undefined
  orderField17: string | undefined
  orderField18: string | undefined
  orderField19: string | undefined
  orderField20: string | undefined
  factoryId: string | undefined
  id: string | undefined
}
