export interface ApsMakeCapacityGoods {
  factoryId?: string | undefined
  goodsId?: string | undefined
  makeCapacityQuantity?: string | undefined
  year?: string | undefined
  month?: string | undefined
  dayMin1?: string | undefined
  dayMax1?: string | undefined
  dayMin2?: string | undefined
  dayMax2?: string | undefined
  dayMin3?: string | undefined
  dayMax3?: string | undefined
  dayMin4?: string | undefined
  dayMax4?: string | undefined
  dayMin5?: string | undefined
  dayMax5?: string | undefined
  dayMin6?: string | undefined
  dayMax6?: string | undefined
  dayMin7?: string | undefined
  dayMax7?: string | undefined
  dayMin8?: string | undefined
  dayMax8?: string | undefined
  dayMin9?: string | undefined
  dayMax9?: string | undefined
  dayMin10?: string | undefined
  dayMax10?: string | undefined
  dayMin11?: string | undefined
  dayMax11?: string | undefined
  dayMin12?: string | undefined
  dayMax12?: string | undefined
  dayMin13?: string | undefined
  dayMax13?: string | undefined
  dayMin14?: string | undefined
  dayMax14?: string | undefined
  dayMin15?: string | undefined
  dayMax15?: string | undefined
  dayMin16?: string | undefined
  dayMax16?: string | undefined
  dayMin17?: string | undefined
  dayMax17?: string | undefined
  dayMin18?: string | undefined
  dayMax18?: string | undefined
  dayMin19?: string | undefined
  dayMax19?: string | undefined
  dayMin20?: string | undefined
  dayMax20?: string | undefined
  dayMin21?: string | undefined
  dayMax21?: string | undefined
  dayMin22?: string | undefined
  dayMax22?: string | undefined
  dayMin23?: string | undefined
  dayMax23?: string | undefined
  dayMin24?: string | undefined
  dayMax24?: string | undefined
  dayMin25?: string | undefined
  dayMax25?: string | undefined
  dayMin26?: string | undefined
  dayMax26?: string | undefined
  dayMin27?: string | undefined
  dayMax27?: string | undefined
  dayMin28?: string | undefined
  dayMax28?: string | undefined
  dayMin29?: string | undefined
  dayMax29?: string | undefined
  dayMin30?: string | undefined
  dayMax30?: string | undefined
  dayMin31?: string | undefined
  dayMax31?: string | undefined
  id?: string | undefined
}
