#!/bin/bash

# 定义服务器IP变量
SERVER_IP="39.100.100.120"

# 构建应用
yarn build

cd dist/
zip -r aps.zip ./*

cd ..
# 删除远程服务器旧文件
ssh root@${SERVER_IP}  'rm -rf  /opt/aps/* '
echo '旧文件删除成功'

# 上传新文件
scp dist/aps.zip root@${SERVER_IP}:/opt/aps/aps.zip
echo '文件上传成功'

# 解压文件
ssh root@${SERVER_IP}  'unzip -o -d /opt/aps /opt/aps/aps.zip'
echo '文件解压成功'

# 修改文件权限
ssh root@${SERVER_IP}  'sudo chown  -R nginx:nginx  /opt/aps'
echo '授权成功'