export interface ApsSchedulingVersion {
  schedulingVersionNo?: string | undefined
  schedulingVersionName?: string | undefined
  schedulingConstraintsId?: string | undefined
  headerList?: string | undefined
  capacityHeaderList?: string | undefined
  capacityDateList?: string | undefined
  schedulingDayCount?: string | undefined
  versionStep?: number | undefined
  versionStepError?: string | undefined
  bomTotalEndDate?: string | undefined
  startDate?: string | undefined
  useFactoryMakeCapacity?: string | undefined
  useGoodsMakeCapacity?: string | undefined
  useSaleConfigMakeCapacity?: string | undefined
  useProjectConfigMakeCapacity?: string | undefined
  factoryIdList?: string | undefined
  goodsIdList?: string | undefined
  id?: string | undefined
  isFinish?: boolean | undefined
  isNotFinish?: boolean | undefined
}
