export interface ApsOrderGoodsHistory {
  factoryId: string | undefined
  goodsId: string | undefined
  goodsName: string | undefined
  year: string | undefined
  monthCount01: string | undefined
  monthRatio01: string | undefined
  monthCount02: string | undefined
  monthRatio02: string | undefined
  monthCount03: string | undefined
  monthRatio03: string | undefined
  monthCount04: string | undefined
  monthRatio04: string | undefined
  monthCount05: string | undefined
  monthRatio05: string | undefined
  monthCount06: string | undefined
  monthRatio06: string | undefined
  monthCount07: string | undefined
  monthRatio07: string | undefined
  monthCount08: string | undefined
  monthRatio08: string | undefined
  monthCount09: string | undefined
  monthRatio09: string | undefined
  monthCount10: string | undefined
  monthRatio10: string | undefined
  monthCount11: string | undefined
  monthRatio11: string | undefined
  monthCount12: string | undefined
  monthRatio12: string | undefined
  id: string | undefined
}
