export interface ApsOrderGoodsBomKittingVersion {
  kittingVersionNo?: string | undefined
  kittingVersionName?: string | undefined
  kittingVersionSource?: string | undefined
  orderCount?: string | undefined
  kittingSuccessCount?: string | undefined
  kittingFailCount?: string | undefined
  kittingRate?: string | undefined
  kittingStatus?: string | undefined
  kittingMissingBom?: string | undefined
  bizId?: string | undefined
  bizType?: string | undefined
  versionCreateParam?: string | undefined
  createDate?: string | undefined
  factoryId?: string | undefined
  goodsStatusId?: string | undefined
  bomUseDate?: string | undefined
  id?: string | undefined
}
