export interface ApsGoodsForecastMakeBomUse {
  goodsId: string | undefined
  makeMonthId: string | undefined
  bomId: string | undefined
  year: string | undefined
  dayNum1: string | undefined
  dayNum2: string | undefined
  dayNum3: string | undefined
  dayNum4: string | undefined
  dayNum5: string | undefined
  dayNum6: string | undefined
  dayNum7: string | undefined
  dayNum8: string | undefined
  dayNum9: string | undefined
  dayNum10: string | undefined
  dayNum11: string | undefined
  dayNum12: string | undefined
  dayNum13: string | undefined
  dayNum14: string | undefined
  dayNum15: string | undefined
  dayNum16: string | undefined
  dayNum17: string | undefined
  dayNum18: string | undefined
  dayNum19: string | undefined
  dayNum20: string | undefined
  dayNum21: string | undefined
  dayNum22: string | undefined
  dayNum23: string | undefined
  dayNum24: string | undefined
  dayNum25: string | undefined
  dayNum26: string | undefined
  dayNum27: string | undefined
  dayNum28: string | undefined
  dayNum29: string | undefined
  dayNum30: string | undefined
  dayNum31: string | undefined
  dayNum32: string | undefined
  dayNum33: string | undefined
  dayNum34: string | undefined
  dayNum35: string | undefined
  dayNum36: string | undefined
  dayNum37: string | undefined
  dayNum38: string | undefined
  dayNum39: string | undefined
  dayNum40: string | undefined
  dayNum41: string | undefined
  dayNum42: string | undefined
  dayNum43: string | undefined
  dayNum44: string | undefined
  dayNum45: string | undefined
  dayNum46: string | undefined
  dayNum47: string | undefined
  dayNum48: string | undefined
  dayNum49: string | undefined
  dayNum50: string | undefined
  dayNum51: string | undefined
  dayNum52: string | undefined
  dayNum53: string | undefined
  dayNum54: string | undefined
  dayNum55: string | undefined
  dayNum56: string | undefined
  dayNum57: string | undefined
  dayNum58: string | undefined
  dayNum59: string | undefined
  dayNum60: string | undefined
  dayNum61: string | undefined
  dayNum62: string | undefined
  dayNum63: string | undefined
  dayNum64: string | undefined
  dayNum65: string | undefined
  dayNum66: string | undefined
  dayNum67: string | undefined
  dayNum68: string | undefined
  dayNum69: string | undefined
  dayNum70: string | undefined
  dayNum71: string | undefined
  dayNum72: string | undefined
  dayNum73: string | undefined
  dayNum74: string | undefined
  dayNum75: string | undefined
  dayNum76: string | undefined
  dayNum77: string | undefined
  dayNum78: string | undefined
  dayNum79: string | undefined
  dayNum80: string | undefined
  dayNum81: string | undefined
  dayNum82: string | undefined
  dayNum83: string | undefined
  dayNum84: string | undefined
  dayNum85: string | undefined
  dayNum86: string | undefined
  dayNum87: string | undefined
  dayNum88: string | undefined
  dayNum89: string | undefined
  dayNum90: string | undefined
  dayNum91: string | undefined
  dayNum92: string | undefined
  dayNum93: string | undefined
  dayNum94: string | undefined
  dayNum95: string | undefined
  dayNum96: string | undefined
  dayNum97: string | undefined
  dayNum98: string | undefined
  dayNum99: string | undefined
  dayNum100: string | undefined
  dayNum101: string | undefined
  dayNum102: string | undefined
  dayNum103: string | undefined
  dayNum104: string | undefined
  dayNum105: string | undefined
  dayNum106: string | undefined
  dayNum107: string | undefined
  dayNum108: string | undefined
  dayNum109: string | undefined
  dayNum110: string | undefined
  dayNum111: string | undefined
  dayNum112: string | undefined
  dayNum113: string | undefined
  dayNum114: string | undefined
  dayNum115: string | undefined
  dayNum116: string | undefined
  dayNum117: string | undefined
  dayNum118: string | undefined
  dayNum119: string | undefined
  dayNum120: string | undefined
  dayNum121: string | undefined
  dayNum122: string | undefined
  dayNum123: string | undefined
  dayNum124: string | undefined
  dayNum125: string | undefined
  dayNum126: string | undefined
  dayNum127: string | undefined
  dayNum128: string | undefined
  dayNum129: string | undefined
  dayNum130: string | undefined
  dayNum131: string | undefined
  dayNum132: string | undefined
  dayNum133: string | undefined
  dayNum134: string | undefined
  dayNum135: string | undefined
  dayNum136: string | undefined
  dayNum137: string | undefined
  dayNum138: string | undefined
  dayNum139: string | undefined
  dayNum140: string | undefined
  dayNum141: string | undefined
  dayNum142: string | undefined
  dayNum143: string | undefined
  dayNum144: string | undefined
  dayNum145: string | undefined
  dayNum146: string | undefined
  dayNum147: string | undefined
  dayNum148: string | undefined
  dayNum149: string | undefined
  dayNum150: string | undefined
  dayNum151: string | undefined
  dayNum152: string | undefined
  dayNum153: string | undefined
  dayNum154: string | undefined
  dayNum155: string | undefined
  dayNum156: string | undefined
  dayNum157: string | undefined
  dayNum158: string | undefined
  dayNum159: string | undefined
  dayNum160: string | undefined
  dayNum161: string | undefined
  dayNum162: string | undefined
  dayNum163: string | undefined
  dayNum164: string | undefined
  dayNum165: string | undefined
  dayNum166: string | undefined
  dayNum167: string | undefined
  dayNum168: string | undefined
  dayNum169: string | undefined
  dayNum170: string | undefined
  dayNum171: string | undefined
  dayNum172: string | undefined
  dayNum173: string | undefined
  dayNum174: string | undefined
  dayNum175: string | undefined
  dayNum176: string | undefined
  dayNum177: string | undefined
  dayNum178: string | undefined
  dayNum179: string | undefined
  dayNum180: string | undefined
  dayNum181: string | undefined
  dayNum182: string | undefined
  dayNum183: string | undefined
  dayNum184: string | undefined
  dayNum185: string | undefined
  dayNum186: string | undefined
  dayNum187: string | undefined
  dayNum188: string | undefined
  dayNum189: string | undefined
  dayNum190: string | undefined
  dayNum191: string | undefined
  dayNum192: string | undefined
  dayNum193: string | undefined
  dayNum194: string | undefined
  dayNum195: string | undefined
  dayNum196: string | undefined
  dayNum197: string | undefined
  dayNum198: string | undefined
  dayNum199: string | undefined
  dayNum200: string | undefined
  dayNum201: string | undefined
  dayNum202: string | undefined
  dayNum203: string | undefined
  dayNum204: string | undefined
  dayNum205: string | undefined
  dayNum206: string | undefined
  dayNum207: string | undefined
  dayNum208: string | undefined
  dayNum209: string | undefined
  dayNum210: string | undefined
  dayNum211: string | undefined
  dayNum212: string | undefined
  dayNum213: string | undefined
  dayNum214: string | undefined
  dayNum215: string | undefined
  dayNum216: string | undefined
  dayNum217: string | undefined
  dayNum218: string | undefined
  dayNum219: string | undefined
  dayNum220: string | undefined
  dayNum221: string | undefined
  dayNum222: string | undefined
  dayNum223: string | undefined
  dayNum224: string | undefined
  dayNum225: string | undefined
  dayNum226: string | undefined
  dayNum227: string | undefined
  dayNum228: string | undefined
  dayNum229: string | undefined
  dayNum230: string | undefined
  dayNum231: string | undefined
  dayNum232: string | undefined
  dayNum233: string | undefined
  dayNum234: string | undefined
  dayNum235: string | undefined
  dayNum236: string | undefined
  dayNum237: string | undefined
  dayNum238: string | undefined
  dayNum239: string | undefined
  dayNum240: string | undefined
  dayNum241: string | undefined
  dayNum242: string | undefined
  dayNum243: string | undefined
  dayNum244: string | undefined
  dayNum245: string | undefined
  dayNum246: string | undefined
  dayNum247: string | undefined
  dayNum248: string | undefined
  dayNum249: string | undefined
  dayNum250: string | undefined
  dayNum251: string | undefined
  dayNum252: string | undefined
  dayNum253: string | undefined
  dayNum254: string | undefined
  dayNum255: string | undefined
  dayNum256: string | undefined
  dayNum257: string | undefined
  dayNum258: string | undefined
  dayNum259: string | undefined
  dayNum260: string | undefined
  dayNum261: string | undefined
  dayNum262: string | undefined
  dayNum263: string | undefined
  dayNum264: string | undefined
  dayNum265: string | undefined
  dayNum266: string | undefined
  dayNum267: string | undefined
  dayNum268: string | undefined
  dayNum269: string | undefined
  dayNum270: string | undefined
  dayNum271: string | undefined
  dayNum272: string | undefined
  dayNum273: string | undefined
  dayNum274: string | undefined
  dayNum275: string | undefined
  dayNum276: string | undefined
  dayNum277: string | undefined
  dayNum278: string | undefined
  dayNum279: string | undefined
  dayNum280: string | undefined
  dayNum281: string | undefined
  dayNum282: string | undefined
  dayNum283: string | undefined
  dayNum284: string | undefined
  dayNum285: string | undefined
  dayNum286: string | undefined
  dayNum287: string | undefined
  dayNum288: string | undefined
  dayNum289: string | undefined
  dayNum290: string | undefined
  dayNum291: string | undefined
  dayNum292: string | undefined
  dayNum293: string | undefined
  dayNum294: string | undefined
  dayNum295: string | undefined
  dayNum296: string | undefined
  dayNum297: string | undefined
  dayNum298: string | undefined
  dayNum299: string | undefined
  dayNum300: string | undefined
  dayNum301: string | undefined
  dayNum302: string | undefined
  dayNum303: string | undefined
  dayNum304: string | undefined
  dayNum305: string | undefined
  dayNum306: string | undefined
  dayNum307: string | undefined
  dayNum308: string | undefined
  dayNum309: string | undefined
  dayNum310: string | undefined
  dayNum311: string | undefined
  dayNum312: string | undefined
  dayNum313: string | undefined
  dayNum314: string | undefined
  dayNum315: string | undefined
  dayNum316: string | undefined
  dayNum317: string | undefined
  dayNum318: string | undefined
  dayNum319: string | undefined
  dayNum320: string | undefined
  dayNum321: string | undefined
  dayNum322: string | undefined
  dayNum323: string | undefined
  dayNum324: string | undefined
  dayNum325: string | undefined
  dayNum326: string | undefined
  dayNum327: string | undefined
  dayNum328: string | undefined
  dayNum329: string | undefined
  dayNum330: string | undefined
  dayNum331: string | undefined
  dayNum332: string | undefined
  dayNum333: string | undefined
  dayNum334: string | undefined
  dayNum335: string | undefined
  dayNum336: string | undefined
  dayNum337: string | undefined
  dayNum338: string | undefined
  dayNum339: string | undefined
  dayNum340: string | undefined
  dayNum341: string | undefined
  dayNum342: string | undefined
  dayNum343: string | undefined
  dayNum344: string | undefined
  dayNum345: string | undefined
  dayNum346: string | undefined
  dayNum347: string | undefined
  dayNum348: string | undefined
  dayNum349: string | undefined
  dayNum350: string | undefined
  dayNum351: string | undefined
  dayNum352: string | undefined
  dayNum353: string | undefined
  dayNum354: string | undefined
  dayNum355: string | undefined
  dayNum356: string | undefined
  dayNum357: string | undefined
  dayNum358: string | undefined
  dayNum359: string | undefined
  dayNum360: string | undefined
  dayNum361: string | undefined
  dayNum362: string | undefined
  dayNum363: string | undefined
  dayNum364: string | undefined
  dayNum365: string | undefined
  dayNum366: string | undefined
  factoryId: string | undefined
  makeSaleConfigId: string | undefined
  id: string | undefined
}
