export interface ApsGoodsBomBuyPlanItem {
  buyPlanId: string | undefined
  year: string | undefined
  bomId: string | undefined
  goodsBomId: string | undefined
  bomCode: string | undefined
  bomName: string | undefined
  bomUsage: string | undefined
  bomUnit: string | undefined
  bomCostPrice: string | undefined
  bomCostPriceUnit: string | undefined
  bomUseWorkStation: string | undefined
  bomUseDay1: string | undefined
  bomUseDay2: string | undefined
  bomUseDay3: string | undefined
  bomUseDay4: string | undefined
  bomUseDay5: string | undefined
  bomUseDay6: string | undefined
  bomUseDay7: string | undefined
  bomUseDay8: string | undefined
  bomUseDay9: string | undefined
  bomUseDay10: string | undefined
  bomUseDay11: string | undefined
  bomUseDay12: string | undefined
  bomUseDay13: string | undefined
  bomUseDay14: string | undefined
  bomUseDay15: string | undefined
  bomUseDay16: string | undefined
  bomUseDay17: string | undefined
  bomUseDay18: string | undefined
  bomUseDay19: string | undefined
  bomUseDay20: string | undefined
  bomUseDay21: string | undefined
  bomUseDay22: string | undefined
  bomUseDay23: string | undefined
  bomUseDay24: string | undefined
  bomUseDay25: string | undefined
  bomUseDay26: string | undefined
  bomUseDay27: string | undefined
  bomUseDay28: string | undefined
  bomUseDay29: string | undefined
  bomUseDay30: string | undefined
  bomUseDay31: string | undefined
  bomUseDay32: string | undefined
  bomUseDay33: string | undefined
  bomUseDay34: string | undefined
  bomUseDay35: string | undefined
  bomUseDay36: string | undefined
  bomUseDay37: string | undefined
  bomUseDay38: string | undefined
  bomUseDay39: string | undefined
  bomUseDay40: string | undefined
  bomUseDay41: string | undefined
  bomUseDay42: string | undefined
  bomUseDay43: string | undefined
  bomUseDay44: string | undefined
  bomUseDay45: string | undefined
  bomUseDay46: string | undefined
  bomUseDay47: string | undefined
  bomUseDay48: string | undefined
  bomUseDay49: string | undefined
  bomUseDay50: string | undefined
  bomUseDay51: string | undefined
  bomUseDay52: string | undefined
  bomUseDay53: string | undefined
  bomUseDay54: string | undefined
  bomUseDay55: string | undefined
  bomUseDay56: string | undefined
  bomUseDay57: string | undefined
  bomUseDay58: string | undefined
  bomUseDay59: string | undefined
  bomUseDay60: string | undefined
  bomUseDay61: string | undefined
  bomUseDay62: string | undefined
  bomUseDay63: string | undefined
  bomUseDay64: string | undefined
  bomUseDay65: string | undefined
  bomUseDay66: string | undefined
  bomUseDay67: string | undefined
  bomUseDay68: string | undefined
  bomUseDay69: string | undefined
  bomUseDay70: string | undefined
  bomUseDay71: string | undefined
  bomUseDay72: string | undefined
  bomUseDay73: string | undefined
  bomUseDay74: string | undefined
  bomUseDay75: string | undefined
  bomUseDay76: string | undefined
  bomUseDay77: string | undefined
  bomUseDay78: string | undefined
  bomUseDay79: string | undefined
  bomUseDay80: string | undefined
  bomUseDay81: string | undefined
  bomUseDay82: string | undefined
  bomUseDay83: string | undefined
  bomUseDay84: string | undefined
  bomUseDay85: string | undefined
  bomUseDay86: string | undefined
  bomUseDay87: string | undefined
  bomUseDay88: string | undefined
  bomUseDay89: string | undefined
  bomUseDay90: string | undefined
  bomUseDay91: string | undefined
  bomUseDay92: string | undefined
  bomUseDay93: string | undefined
  bomUseDay94: string | undefined
  bomUseDay95: string | undefined
  bomUseDay96: string | undefined
  bomUseDay97: string | undefined
  bomUseDay98: string | undefined
  bomUseDay99: string | undefined
  bomUseDay100: string | undefined
  bomUseDay101: string | undefined
  bomUseDay102: string | undefined
  bomUseDay103: string | undefined
  bomUseDay104: string | undefined
  bomUseDay105: string | undefined
  bomUseDay106: string | undefined
  bomUseDay107: string | undefined
  bomUseDay108: string | undefined
  bomUseDay109: string | undefined
  bomUseDay110: string | undefined
  bomUseDay111: string | undefined
  bomUseDay112: string | undefined
  bomUseDay113: string | undefined
  bomUseDay114: string | undefined
  bomUseDay115: string | undefined
  bomUseDay116: string | undefined
  bomUseDay117: string | undefined
  bomUseDay118: string | undefined
  bomUseDay119: string | undefined
  bomUseDay120: string | undefined
  bomUseDay121: string | undefined
  bomUseDay122: string | undefined
  bomUseDay123: string | undefined
  bomUseDay124: string | undefined
  bomUseDay125: string | undefined
  bomUseDay126: string | undefined
  bomUseDay127: string | undefined
  bomUseDay128: string | undefined
  bomUseDay129: string | undefined
  bomUseDay130: string | undefined
  bomUseDay131: string | undefined
  bomUseDay132: string | undefined
  bomUseDay133: string | undefined
  bomUseDay134: string | undefined
  bomUseDay135: string | undefined
  bomUseDay136: string | undefined
  bomUseDay137: string | undefined
  bomUseDay138: string | undefined
  bomUseDay139: string | undefined
  bomUseDay140: string | undefined
  bomUseDay141: string | undefined
  bomUseDay142: string | undefined
  bomUseDay143: string | undefined
  bomUseDay144: string | undefined
  bomUseDay145: string | undefined
  bomUseDay146: string | undefined
  bomUseDay147: string | undefined
  bomUseDay148: string | undefined
  bomUseDay149: string | undefined
  bomUseDay150: string | undefined
  bomUseDay151: string | undefined
  bomUseDay152: string | undefined
  bomUseDay153: string | undefined
  bomUseDay154: string | undefined
  bomUseDay155: string | undefined
  bomUseDay156: string | undefined
  bomUseDay157: string | undefined
  bomUseDay158: string | undefined
  bomUseDay159: string | undefined
  bomUseDay160: string | undefined
  bomUseDay161: string | undefined
  bomUseDay162: string | undefined
  bomUseDay163: string | undefined
  bomUseDay164: string | undefined
  bomUseDay165: string | undefined
  bomUseDay166: string | undefined
  bomUseDay167: string | undefined
  bomUseDay168: string | undefined
  bomUseDay169: string | undefined
  bomUseDay170: string | undefined
  bomUseDay171: string | undefined
  bomUseDay172: string | undefined
  bomUseDay173: string | undefined
  bomUseDay174: string | undefined
  bomUseDay175: string | undefined
  bomUseDay176: string | undefined
  bomUseDay177: string | undefined
  bomUseDay178: string | undefined
  bomUseDay179: string | undefined
  bomUseDay180: string | undefined
  bomUseDay181: string | undefined
  bomUseDay182: string | undefined
  bomUseDay183: string | undefined
  bomUseDay184: string | undefined
  bomUseDay185: string | undefined
  bomUseDay186: string | undefined
  bomUseDay187: string | undefined
  bomUseDay188: string | undefined
  bomUseDay189: string | undefined
  bomUseDay190: string | undefined
  bomUseDay191: string | undefined
  bomUseDay192: string | undefined
  bomUseDay193: string | undefined
  bomUseDay194: string | undefined
  bomUseDay195: string | undefined
  bomUseDay196: string | undefined
  bomUseDay197: string | undefined
  bomUseDay198: string | undefined
  bomUseDay199: string | undefined
  bomUseDay200: string | undefined
  bomUseDay201: string | undefined
  bomUseDay202: string | undefined
  bomUseDay203: string | undefined
  bomUseDay204: string | undefined
  bomUseDay205: string | undefined
  bomUseDay206: string | undefined
  bomUseDay207: string | undefined
  bomUseDay208: string | undefined
  bomUseDay209: string | undefined
  bomUseDay210: string | undefined
  bomUseDay211: string | undefined
  bomUseDay212: string | undefined
  bomUseDay213: string | undefined
  bomUseDay214: string | undefined
  bomUseDay215: string | undefined
  bomUseDay216: string | undefined
  bomUseDay217: string | undefined
  bomUseDay218: string | undefined
  bomUseDay219: string | undefined
  bomUseDay220: string | undefined
  bomUseDay221: string | undefined
  bomUseDay222: string | undefined
  bomUseDay223: string | undefined
  bomUseDay224: string | undefined
  bomUseDay225: string | undefined
  bomUseDay226: string | undefined
  bomUseDay227: string | undefined
  bomUseDay228: string | undefined
  bomUseDay229: string | undefined
  bomUseDay230: string | undefined
  bomUseDay231: string | undefined
  bomUseDay232: string | undefined
  bomUseDay233: string | undefined
  bomUseDay234: string | undefined
  bomUseDay235: string | undefined
  bomUseDay236: string | undefined
  bomUseDay237: string | undefined
  bomUseDay238: string | undefined
  bomUseDay239: string | undefined
  bomUseDay240: string | undefined
  bomUseDay241: string | undefined
  bomUseDay242: string | undefined
  bomUseDay243: string | undefined
  bomUseDay244: string | undefined
  bomUseDay245: string | undefined
  bomUseDay246: string | undefined
  bomUseDay247: string | undefined
  bomUseDay248: string | undefined
  bomUseDay249: string | undefined
  bomUseDay250: string | undefined
  bomUseDay251: string | undefined
  bomUseDay252: string | undefined
  bomUseDay253: string | undefined
  bomUseDay254: string | undefined
  bomUseDay255: string | undefined
  bomUseDay256: string | undefined
  bomUseDay257: string | undefined
  bomUseDay258: string | undefined
  bomUseDay259: string | undefined
  bomUseDay260: string | undefined
  bomUseDay261: string | undefined
  bomUseDay262: string | undefined
  bomUseDay263: string | undefined
  bomUseDay264: string | undefined
  bomUseDay265: string | undefined
  bomUseDay266: string | undefined
  bomUseDay267: string | undefined
  bomUseDay268: string | undefined
  bomUseDay269: string | undefined
  bomUseDay270: string | undefined
  bomUseDay271: string | undefined
  bomUseDay272: string | undefined
  bomUseDay273: string | undefined
  bomUseDay274: string | undefined
  bomUseDay275: string | undefined
  bomUseDay276: string | undefined
  bomUseDay277: string | undefined
  bomUseDay278: string | undefined
  bomUseDay279: string | undefined
  bomUseDay280: string | undefined
  bomUseDay281: string | undefined
  bomUseDay282: string | undefined
  bomUseDay283: string | undefined
  bomUseDay284: string | undefined
  bomUseDay285: string | undefined
  bomUseDay286: string | undefined
  bomUseDay287: string | undefined
  bomUseDay288: string | undefined
  bomUseDay289: string | undefined
  bomUseDay290: string | undefined
  bomUseDay291: string | undefined
  bomUseDay292: string | undefined
  bomUseDay293: string | undefined
  bomUseDay294: string | undefined
  bomUseDay295: string | undefined
  bomUseDay296: string | undefined
  bomUseDay297: string | undefined
  bomUseDay298: string | undefined
  bomUseDay299: string | undefined
  bomUseDay300: string | undefined
  bomUseDay301: string | undefined
  bomUseDay302: string | undefined
  bomUseDay303: string | undefined
  bomUseDay304: string | undefined
  bomUseDay305: string | undefined
  bomUseDay306: string | undefined
  bomUseDay307: string | undefined
  bomUseDay308: string | undefined
  bomUseDay309: string | undefined
  bomUseDay310: string | undefined
  bomUseDay311: string | undefined
  bomUseDay312: string | undefined
  bomUseDay313: string | undefined
  bomUseDay314: string | undefined
  bomUseDay315: string | undefined
  bomUseDay316: string | undefined
  bomUseDay317: string | undefined
  bomUseDay318: string | undefined
  bomUseDay319: string | undefined
  bomUseDay320: string | undefined
  bomUseDay321: string | undefined
  bomUseDay322: string | undefined
  bomUseDay323: string | undefined
  bomUseDay324: string | undefined
  bomUseDay325: string | undefined
  bomUseDay326: string | undefined
  bomUseDay327: string | undefined
  bomUseDay328: string | undefined
  bomUseDay329: string | undefined
  bomUseDay330: string | undefined
  bomUseDay331: string | undefined
  bomUseDay332: string | undefined
  bomUseDay333: string | undefined
  bomUseDay334: string | undefined
  bomUseDay335: string | undefined
  bomUseDay336: string | undefined
  bomUseDay337: string | undefined
  bomUseDay338: string | undefined
  bomUseDay339: string | undefined
  bomUseDay340: string | undefined
  bomUseDay341: string | undefined
  bomUseDay342: string | undefined
  bomUseDay343: string | undefined
  bomUseDay344: string | undefined
  bomUseDay345: string | undefined
  bomUseDay346: string | undefined
  bomUseDay347: string | undefined
  bomUseDay348: string | undefined
  bomUseDay349: string | undefined
  bomUseDay350: string | undefined
  bomUseDay351: string | undefined
  bomUseDay352: string | undefined
  bomUseDay353: string | undefined
  bomUseDay354: string | undefined
  bomUseDay355: string | undefined
  bomUseDay356: string | undefined
  bomUseDay357: string | undefined
  bomUseDay358: string | undefined
  bomUseDay359: string | undefined
  bomUseDay360: string | undefined
  bomUseDay361: string | undefined
  bomUseDay362: string | undefined
  bomUseDay363: string | undefined
  bomUseDay364: string | undefined
  bomUseDay365: string | undefined
  bomUseDay366: string | undefined
  factoryId: string | undefined
  isFollow: string | undefined
  id: string | undefined
}
