export interface ApsGoodsForecastMainSaleData {
  goodsId: string | undefined
  saleConfigCode: string | undefined
  year: string | undefined
  month01: string | undefined
  month02: string | undefined
  month03: string | undefined
  month04: string | undefined
  month05: string | undefined
  month06: string | undefined
  month07: string | undefined
  month08: string | undefined
  month09: string | undefined
  month10: string | undefined
  month11: string | undefined
  month12: string | undefined
  forecastMainId: string | undefined
  id: string | undefined
}
