export interface ApsMakeCapacityFactory {
  factoryId?: undefined | string
  makeCapacityQuantity?: undefined | string
  year?: undefined | string
  month?: undefined | string
  dayMin1?: undefined | string
  dayMax1?: undefined | string
  dayMin2?: undefined | string
  dayMax2?: undefined | string
  dayMin3?: undefined | string
  dayMax3?: undefined | string
  dayMin4?: undefined | string
  dayMax4?: undefined | string
  dayMin5?: undefined | string
  dayMax5?: undefined | string
  dayMin6?: undefined | string
  dayMax6?: undefined | string
  dayMin7?: undefined | string
  dayMax7?: undefined | string
  dayMin8?: undefined | string
  dayMax8?: undefined | string
  dayMin9?: undefined | string
  dayMax9?: undefined | string
  dayMin10?: undefined | string
  dayMax10?: undefined | string
  dayMin11?: undefined | string
  dayMax11?: undefined | string
  dayMin12?: undefined | string
  dayMax12?: undefined | string
  dayMin13?: undefined | string
  dayMax13?: undefined | string
  dayMin14?: undefined | string
  dayMax14?: undefined | string
  dayMin15?: undefined | string
  dayMax15?: undefined | string
  dayMin16?: undefined | string
  dayMax16?: undefined | string
  dayMin17?: undefined | string
  dayMax17?: undefined | string
  dayMin18?: undefined | string
  dayMax18?: undefined | string
  dayMin19?: undefined | string
  dayMax19?: undefined | string
  dayMin20?: undefined | string
  dayMax20?: undefined | string
  dayMin21?: undefined | string
  dayMax21?: undefined | string
  dayMin22?: undefined | string
  dayMax22?: undefined | string
  dayMin23?: undefined | string
  dayMax23?: undefined | string
  dayMin24?: undefined | string
  dayMax24?: undefined | string
  dayMin25?: undefined | string
  dayMax25?: undefined | string
  dayMin26?: undefined | string
  dayMax26?: undefined | string
  dayMin27?: undefined | string
  dayMax27?: undefined | string
  dayMin28?: undefined | string
  dayMax28?: undefined | string
  dayMin29?: undefined | string
  dayMax29?: undefined | string
  dayMin30?: undefined | string
  dayMax30?: undefined | string
  dayMin31?: undefined | string
  dayMax31?: undefined | string
  id?: undefined | string
}
