export interface ApsMakeCapacityFactory {
  factoryId: string
  makeCapacityQuantity: string
  year: string
  month: string
  dayMin1: string
  dayMax1: string
  dayMin2: string
  dayMax2: string
  dayMin3: string
  dayMax3: string
  dayMin4: string
  dayMax4: string
  dayMin5: string
  dayMax5: string
  dayMin6: string
  dayMax6: string
  dayMin7: string
  dayMax7: string
  dayMin8: string
  dayMax8: string
  dayMin9: string
  dayMax9: string
  dayMin10: string
  dayMax10: string
  dayMin11: string
  dayMax11: string
  dayMin12: string
  dayMax12: string
  dayMin13: string
  dayMax13: string
  dayMin14: string
  dayMax14: string
  dayMin15: string
  dayMax15: string
  dayMin16: string
  dayMax16: string
  dayMin17: string
  dayMax17: string
  dayMin18: string
  dayMax18: string
  dayMin19: string
  dayMax19: string
  dayMin20: string
  dayMax20: string
  dayMin21: string
  dayMax21: string
  dayMin22: string
  dayMax22: string
  dayMin23: string
  dayMax23: string
  dayMin24: string
  dayMax24: string
  dayMin25: string
  dayMax25: string
  dayMin26: string
  dayMax26: string
  dayMin27: string
  dayMax27: string
  dayMin28: string
  dayMax28: string
  dayMin29: string
  dayMax29: string
  dayMin30: string
  dayMax30: string
  dayMin31: string
  dayMax31: string
  id: string
}

