export interface ApsRollingForecastFactoryCapacity {
  factoryId?: string | undefined
  year?: string | undefined
  month?: string | undefined
  day01?: string | undefined
  day02?: string | undefined
  day03?: string | undefined
  day04?: string | undefined
  day05?: string | undefined
  day06?: string | undefined
  day07?: string | undefined
  day08?: string | undefined
  day09?: string | undefined
  day10?: string | undefined
  day11?: string | undefined
  day12?: string | undefined
  day13?: string | undefined
  day14?: string | undefined
  day15?: string | undefined
  day16?: string | undefined
  day17?: string | undefined
  day18?: string | undefined
  day19?: string | undefined
  day20?: string | undefined
  day21?: string | undefined
  day22?: string | undefined
  day23?: string | undefined
  day24?: string | undefined
  day25?: string | undefined
  day26?: string | undefined
  day27?: string | undefined
  day28?: string | undefined
  day29?: string | undefined
  day30?: string | undefined
  day31?: string | undefined
  capacity?: string | undefined
  id?: string | undefined
  capacityList?: any[] | undefined
}
