export interface ApsOrderGoodsBom {
  orderId: string | undefined
  goodsBomId: string | undefined
  goodsId: string | undefined
  groupId: string | undefined
  bomId: string | undefined
  bomCode: string | undefined
  bomName: string | undefined
  bomUsage: string | undefined
  bomUnit: string | undefined
  bomCostPrice: string | undefined
  bomCostPriceUnit: string | undefined
  bomUseWorkStation: string | undefined
  bomUseExpression: string | undefined
  bomInventory: string | undefined
  isFollow: string | undefined
  factoryId: string | undefined
  goodsStatusId: string | undefined
  bomUseDate: string | undefined
  id: string | undefined
}
